### ISSUE TITLE
CT item not found in array

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#101]
```
isotopes-and-atomic-mass : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/isotopes-and-atomic-mass/isotopes-and-atomic-mass_en.html?continuousTest=%7B%22test%22%3A%5B%22isotopes-and-atomic-mass%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1612448066994%22%2C%22timestamp%22%3A1612451034563%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000
Uncaught Error: Assertion failed: item not found in Array
Error: Assertion failed: item not found in Array
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/assert/js/assert.js:25:13)
at arrayRemove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/phet-core/js/arrayRemove.js:19:13)
at Proxy.remove (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/axon/js/createObservableArray.js:345:33)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/isotopes-and-atomic-mass/js/mix-isotopes/model/MixIsotopesModel.js:623:27
at Proxy.forEach (<anonymous>)
at MixIsotopesModel.removeAllIsotopesFromTestChamberAndModel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/isotopes-and-atomic-mass/js/mix-isotopes/model/MixIsotopesModel.js:622:42)
at MixIsotopesModel.setAtomConfiguration (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/isotopes-and-atomic-mass/js/mix-isotopes/model/MixIsotopesModel.js:373:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/isotopes-and-atomic-mass/js/mix-isotopes/model/MixIsotopesModel.js:126:12
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/axon/js/TinyEmitter.js:71:18)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1612448066994/axon/js/Emitter.js:35:29
id: Bayes Chrome
Snapshot from 2/4/2021, 7:14:26 AM
```

**Comment by jbphet** [comment]
Here's how to duplicate this easily:
- go to 2nd screen
- with one finger, pull a hydrogen atom out of a bucket and hold it outside if the chamber
- with another finger, and without letting go of the atom, use the radio buttons to switch to the "Nature's Mix" view
- immediately switch back to the "My Mix" view

**Comment by jbphet** [comment]
I did a bunch of code cleanup and fixed a different multi-touch issue as part of the commit to address this, so I should explain what was happening and what fixed it.

The problem existed because the code to clean up the model state when switching modes wasn't properly deleting atoms that weren't in the test chamber or associated with a bucket.  This situation isn't possible in non-multi-touch situations, but now the multi-touch fuzzing is on, it *is* possible.  I improved the code to do a better job of getting rid of all of the isotopes in the model when switching modes.  The main change was to `MixIsotopesModel.removeAllIsotopesFromTestChamberAndModel`, so look at the history there to better understand what changed.

**Comment by jbphet** [comment]
@KatieWoe - I'd like some regression testing done on the master version of this sim to verify that this didn't break anything. The testing should focus on multi-touch on the 2nd screen, particularly involving changing modes while dragging particles around.

**Comment by KatieWoe** [comment]
If you are dragging a particle, switch atom type, but don't drop the particle, then come back to the original atom type, that particle will be gone. It does not seem to disappear if you drop it while in the other atom scene.
![multitouchswitchscene](https://user-images.githubusercontent.com/41024075/107095732-8e172880-67c6-11eb-82bc-418db83b333b.gif)

**Comment by jbphet** [comment]
The missing particle occurred because it was neither in the "test chamber" nor the bucket when the state of the screen was recorded.  This is impossible in non-multi-touch situations, but we need to handle it now.  I've added code to cancel interactions and essentially force the particles back into their home bucket when this situation arises.

**Comment by jbphet** [comment]
@KatieWoe - good observation on the missing particle problem.  I've addressed this too now, and I ran the multi-fuzz test for 10 minutes with no issues, and CT looks clear since these commits were made.  I'm assign this at #102 back to you for a bit more regression testing and, if all looks good, they can be closed.

**Comment by KatieWoe** [comment]
One more instance where this can happen. If you are holding the atom above the play area, switch scenes but don't let go of the atom, and come back, the atom is gone.
![overplayarea](https://user-images.githubusercontent.com/41024075/107404847-e9e1fa00-6ac3-11eb-8191-20b1b2438d5c.gif)

**Comment by jbphet** [comment]
Yep, good find.  I've addressed this one by implementing better handling of state storage when a particle is being dragged when a switch of the view state occurs.  @KatieWoe - Please test again and see whether we're there yet.

**Comment by KatieWoe** [comment]
I don't see any problems on master. I focused on the second screen and the behavior of the atoms as you dragged them and switched scenes. Are there any other aspects that could be affected I should test?

**Comment by jbphet** [comment]
@KatieWoe said:

> Are there any other aspects that could be affected I should test?

Not that I'm aware of.

As far as next steps go, I don't think that this is significant enough to warrant a maintenance release, so I think I'll mark it as fixed and awaiting deployment, and will unassign.  The next time this is deployed from master, we should have this tested as part of the deployment process to make sure that it is indeed fully resolved.

**Comment by KatieWoe** [comment]
Closing this for https://github.com/phetsims/qa/issues/832. If this is in error, feel free to reopen.
