### ISSUE TITLE
Need icons for home screen and nav bar

### ISSUE THREAD

**Issue by jbphet** [phetsims/isotopes-and-atomic-mass#4]
This is a multi-screen sim, so icons will be needed for the home screen and nav bar.

**Comment by ariel-phet** [comment]
@ycarpenterphet, this is not high priority since although this sim is in development, it will be a long development cycle as it is being completed by interns.

Feel free to work with our new graphic artist (Mariah on this project). If you want her to do the illustrator work, create a task, give it the "artwork" label and assign it to @amanda-phet for prioritization.

**Comment by ycarpenterphet** [comment]
@ariel-phet I'm unlikely to be able to iterate on this with Mariah before my departure, so I'd suggest assigning someone else for continuity. Depending on the development timeline, perhaps this could be a good starter for Amy H, as she's getting into design?

**Comment by aadish** [comment]
we have these now. Closing
