### ISSUE TITLE
Phrase separated into three keys?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/isotopes-and-atomic-mass#45]
So in 1.0.0-dev.5 I used the ?stringTest=double query and noticed this in the "Abundance in Nature" panel:

![3 keys](https://cloud.githubusercontent.com/assets/5863899/12628330/dd735b3e-c4ff-11e5-8c99-963a17ab000f.PNG)

Does this mean that "Other", "Hydrogen", and "Isotopes" have three separate string keys? If they are, I have a small pet-peeve about keeping context while translating. If a translator were to be using our utility they would be presented with those strings all separately, which in my opinion is not very convenient and may result in an incorrect translation. They might translate these strings as though they were three sepearate words and not used together in a phrase. @aadish is there a way to make them one string?

Tagging @arouinfar since she translates a bunch and her personal preference could be useful :smile:.

And I know the counter argument "That's what the Test button is for!", but it's not hard to imagine that some of our translators don't use it all the time or that maybe they'll not notice this.

For phetsims/tasks/issues/488

**Comment by arouinfar** [comment]
I don't think it's a good idea to ask translators to supply separate strings for "Other" and "Isotopes" because it lacks the appropriate context. It makes the most sense to have the key be something along the lines of "Other {0} Isotopes" where {0} represents the element. The element names will also need to have separate keys, as they vary with locale.

**Comment by aadish** [comment]
fixed, closing
