### ISSUE TITLE
sim fails at startup in requirejs mode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/isotopes-and-atomic-mass#7]
Here's the console log:

![screenshot_485](https://cloud.githubusercontent.com/assets/3046552/6626640/03950748-c8be-11e4-95d0-c83867cb9550.png)

**Comment by jasm32851** [comment]
Hey Chris!

I think that Jesse and I have fixed the error that you mentioned, but I
haven't pushed files yet because I'm trying to figure out how I can import
the .xml file on my mac. Currently IntelliJ throws an error when I try to
import the formatting setting myself. As soon as I figure it out I will
push the files.

Thanks,

James

**Comment by pixelzoom** [comment]
HI James,

When you say “import the formatting settings” do you mean the PhET code style?

The xml file for the PhET code style is `joist/util/phet-idea-code-style.xml`

On Mac, copy it to `$HOME/Library/Preferences/IntelliJIdea14/codestyles/`, restart IDEA, then select it from Preferences->Editor->Code Style.

Chris

**Comment by jasm32851** [comment]
Chris,

Jesse and I realized the problems were stemming from the fact that I had
the IntelliJ Community Edition rather than the Ultimate Edition, but I've
since gotten it figured out. Thanks for your help!

-James

**Comment by aadish** [comment]
This is fixed. Closing
