### ISSUE TITLE
Radio button text on Mix Isotope's Screen

### ISSUE THREAD

**Issue by aadish** [phetsims/isotopes-and-atomic-mass#75]
The width of radio button text on mix isotope screen can be increase a bit
![image](https://cloud.githubusercontent.com/assets/4546788/15520334/0e4cc6f8-21c3-11e6-9e36-8b3c6d372944.png)

**Comment by jbphet** [comment]
I just checked two other translations that tend to have long words, and the "Nature's Mix" label is being scaled down in those too (see screenshots below).  I think it would be worth fixing this so that the strings can be longer and doing a maintenance release.  The current length limit is, I believe, due to the fact that the bucket vs. slider selector control used to be in the same area of the sim with these radio buttons, but since that selector is now positioned just under the isotope chamber, these strings have some room to grow.  Assigning to @aadish to do the maintenance release.

Screenshots (Danish, then Latvian):
![iaam-dutch-string-issue](https://cloud.githubusercontent.com/assets/3082831/15545421/7b4108fa-2259-11e6-82ab-cd53d4818a06.PNG)
![iaam-latvian-string-issue](https://cloud.githubusercontent.com/assets/3082831/15545432/823cc8ba-2259-11e6-95cc-2446863e62cc.PNG)

**Comment by aadish** [comment]
Did a maintenance release and this 06c9e7a85cce8c0459549af0f7eda1a423ec00a6 fixes it

Current screenshot for danish and latvian

![image](https://cloud.githubusercontent.com/assets/4546788/15546403/052c0008-225d-11e6-9c5d-c2baedda6b63.png)

![image](https://cloud.githubusercontent.com/assets/4546788/15546423/18c808e6-225d-11e6-938c-98ebd946a880.png)

Closing it
