### ISSUE TITLE
User reported issue: isotope question

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/isotopes-and-atomic-mass#79]
Reported Sep 26, 2016:

> 
> I am running the Isotopes and Atomic Mass sim with my chemistry students. From my perspective, there are many errors in the content. For example, it is well known that Hydrogen has 3 isotopes yet only 2 are shown (H-3 is missing) Similarly, Carbon is missing the very important C-14, which is used in carbon dating. Fluorine shows F-19 as a sole isotope, when in fact Fluorine has 18 isotopes in total.
> 
> 
> I did not check the other elements, but I suspect I will find the same.?
> 
> 
> Please advise, I will not be able to continue using this sim unless it is corrected.
> 

Maybe @amyh-phet can comment?

**Comment by ariel-phet** [comment]
@oliver-phet I think this user is sort of missing the point of the sim. In the first screen you can build these other isotopes, but the second screen is about abundance in nature.

Yes, it is true fluorine has many other isotopes but they are not abundant in nature. Most of these are supremely unstable (lasting only a few seconds or lasting only 1x10^-20 seconds). Therefore the second screen is focused on where the "average" atomic mass comes from. For something like flourine the average atomic mass IS the mass of Flourine 19, since that is the only isotope laying around in any appreciable quantity.

@oliver-phet please tell the user to watch the sim primer, this is explained there.

@amyh-phet I am not sure if this is adequately addressed in the teacher tips.

**Comment by ariel-phet** [comment]
Or if you want short answer:

"On the second screen only *stable* isotopes are shown so students can investigate how the abundance of stable isotopes affects the average mass"

**Comment by oliver-phet** [comment]
Email to user sent!

**Comment by amyh-phet** [comment]
@oliver-phet  and @ariel-phet    I will update teacher tips accordingly.

**Comment by oliver-phet** [comment]
Ok, I think that's all for this. Can you close this issue once the new tips have been published?

**Comment by amyh-phet** [comment]
Can do!
