### ISSUE TITLE
User suggestion: tritium (trace) abundance

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/isotopes-and-atomic-mass#85]
> I wanted to point out and ask if this particular simulation could be modified to correctly identify Hydrogen-'s (tritium) percent abundance in nature. The simulation indicates 0% although it does exist in trace amounts. I like to use this simulation for better understanding of isotopes but this is misleading to my students.

**Comment by jbphet** [comment]
I looked up the abundance on Wikipedia, and it says "trace".  Maybe we should just add that, and not try to go for a numeric value.  We also say 0% for Carbon-14, but Wikipedia says 1 ppt for it, so perhaps "trace" would be appropriate there too.

@oliver-phet - could you please provide me with the email of the person who contacted you so that I could have a direct dialog with them on good terms for this?

I'm also assigning @ariel-phet and @arouinfar for their input, since the original designers have both left PhET.

I would estimate 2-3 hours to implement this on the release branch (I would release from there, and not from master, to minimize the required testing).

**Comment by arouinfar** [comment]
Looking at [NIST](https://www.nist.gov/pml/atomic-weights-and-isotopic-compositions-relative-atomic-masses) and [IUPAC](http://www.ciaaw.org/isotopic-abundances.htm), H-3 and C-14 are not listed in isotope abundance tables, and the other stable isotopes add up to 100%. The current design of the simulation is in line with with these conventions.

I don't see any particular harm in using "trace" instead of 0% for naturally occurring, albeit radioactive, isotopes. My hesitation with listing H-3 and C-14 with "trace" abundance is that it may be a slippery slope. Would we do the same for F-18, Be-7, and Be-10 which also have trace abundance? 

If we do decide that it'd be worthwhile to switch over to "trace", it might be a good opportunity to send this sim back through a QA cycle so we can pick up Legends of Learning support, so long as QA has the bandwidth for it.

**Comment by jbphet** [comment]
I'd be in favor of doing this.  I feel like it must be a bit confusing for people who are learning this material to understand how something like carbon dating works when the sim says that 0% carbon-14 exists in nature.  "Trace" seems like a reasonable way to do this, and I'd just add support for that readout and value in the sim.  We could do as many isotopes makes sense, having more doesn't imply much extra effort.

**Comment by jbphet** [comment]
I emailed the teach and asked if using the term "trace" seemed appropriate in these circumstances.  The response was:

> Yes sir! Exactly! Thank you for your quick feedback.

**Comment by ariel-phet** [comment]
As for the slippery slope brought up by @arouinfar it looks like the official definition of "trace" is isotopes that are produced by other natural processes

https://en.wikipedia.org/wiki/Trace_radioisotope

So I think we only want to use "trace" in these cases (H-3 and C-14 are such cases). So as long as we are consistent, trace seems acceptable.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! Looking at the Trace Radioisotope wiki article you linked, all of these isotopes should be listed with "trace" abundance:

> Tritium
Beryllium-7
Beryllium-10
Carbon-14
Fluorine-18

@jbphet let's move forward with this change, though I would still like @ariel-phet to weigh in on whether or not we should send the sim through QA to pick up LoL support.

**Comment by ariel-phet** [comment]
@jbphet @arouinfar yes, QA should have the time, would be good.

**Comment by jbphet** [comment]
I've implemented this feature, but there is one design question that should be resolved before an RC is published.  The question is this: How should we handle elements that only have one fully stable isotope, such as beryllium and fluorine?  In the dev version linked below, the behavior for isotopes like hydrogen-3 and carbon-14 seems great, but these both have other isotopes in addition to the trace isotopes that are stable.  This is not the case for Be and F, so I'm not sure what to show in the "Abundance in nature" display when their main stable isotope is selected.  Right now, it just says "100%" and doesn't mention the trace isotopes, but those will show up with "trace" abundance if built by the user.  This behavior seems reasonable to me, since it would be a little confusing to say 100% but also indicate that trace isotopes exist.  However, the fact that other isotopes don't all indicate an abundance of 0% in these cases could also be confusing, so perhaps the right side of the chart should have some sort of note like:
> (other isotopes exist
> in trace amounts)

@arouinfar and @ariel-phet - please try out [this version](https://phet-dev.colorado.edu/html/isotopes-and-atomic-mass/1.1.0-dev.1/phet/isotopes-and-atomic-mass_en_phet.html) and let me know how you think we should handle this case.  We can discuss in a design meeting if you like.

**Comment by arouinfar** [comment]
@jbphet great questions. I think the behavior in 1.1.0-dev.1 looks good!

> Right now, it just says "100%" and doesn't mention the trace isotopes, but those will show up with "trace" abundance if built by the user. This behavior seems reasonable to me, since it would be a little confusing to say 100% but also indicate that trace isotopes exist. 

Agree, that seems perfectly reasonable to me.

> However, the fact that other isotopes don't all indicate an abundance of 0% in these cases could also be confusing

I don't think this is an issue. Let's consider carbon -- the abundance of C-12 and C-13 add up to exactly 100%, but C-14 has a "trace" abundance. This is consistent with the behavior of Be and F, and I think seeing "trace" could be a good starting point for productive class discussion. 

> so perhaps the right side of the chart should have some sort of note like:
>>(other isotopes exist
in trace amounts)

This seems like overkill to me. I think we'd definitely want to update the Teacher Tips to add information about this change, but I don't think we need to clarify in the sim itself.

**Comment by jbphet** [comment]
This issue was briefly discussed in the 3/21/2019 status meeting, and @kathy-phet felt that it would be best to leave it as is in the dev version.  @emily-phet suggested considering having something on the right side of the pie chart indicating that trace amounts of other isotopes exist.  It was also suggested that I contact one of the chemists who has consulted with us on the design of the chem-related sims and get that individual's opinion.

Since @arouinfar, @kathy-phet, and I are all comfortable with the idea of not showing anything on the right side of the pie chart for these Be and F cases, I'm going to go ahead and move forward with a release candidate to add this feature.  I'll run it by @ariel-phet when he is back and the aforementioned chemist to make sure they don't have strong objections.

**Comment by ariel-phet** [comment]
No strong objections from me.

**Comment by jbphet** [comment]
I shared an RC with the teacher who originally reported the issue.  She said,

> Perfect! I can't wait to show my students!

**Comment by jbphet** [comment]
Unassigning until RC testing is complete, see https://github.com/phetsims/QA/issues/300.

**Comment by KatieWoe** [comment]
Wrinkle found in https://github.com/phetsims/isotopes-and-atomic-mass/issues/88 (1.1.0-rc.1)

**Comment by jbphet** [comment]
Support for trace amounts has been added and deployed.  @oliver-phet - do you want to let translators know about this new string?  Once done, this can be closed.

**Comment by oliver-phet** [comment]
Email to translators sent.
