### ISSUE TITLE
Accordion box slightly off screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/isotopes-and-atomic-mass#96]
Minor design bug found in https://github.com/phetsims/QA/issues/310, but present in published version.
When string are longer than normal (double and long) the yellow accordion boxes on the mixture screen go slightly out of bounds.  The +/- boxes are always visible and clickable, but it can look odd. To see this, use either an iPad/iPhone or the dev parameter.
![boxoffedge](https://user-images.githubusercontent.com/41024075/56604570-781f8000-65bf-11e9-9bf3-2a3f69f5404f.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56604576-7ce43400-65bf-11e9-892a-63dec55721ca.png)

**Comment by arouinfar** [comment]
Nice find @KatieWoe.  It seems like the accordion menus don't have an appropriate `maxWidth` @jbphet. Since they are already quite wide, I don't think they need to expand any further for i18n.

Not sure if it's relevant here, but according to https://github.com/phetsims/joist/issues/542#issuecomment-443920171 this sim uses non-standard `layoutBounds`.

**Comment by jbphet** [comment]
I've added `maxWidth` params for these accordion boxes.

**Comment by jbphet** [comment]
Fixed and deployed.  Closing.
