### ISSUE TITLE
'otherIsotopesPattern' translated string not creating line break

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/isotopes-and-atomic-mass#97]
![image](https://user-images.githubusercontent.com/5090275/57087469-5ad46b00-6cbd-11e9-9ee4-dd500bbebbf8.png)
![image](https://user-images.githubusercontent.com/5090275/57087476-60ca4c00-6cbd-11e9-9fe8-5cfb80bc1eae.png)

**Comment by jbphet** [comment]
Well, I can see why the string is being displayed like this.  The Polish strings file `isototpes-and-atomic-mass-strings_pl.json` has the following value for the `otherIsotopesPattern`:
```
"value": "{0}:\\npozostałe\\nizotopy"
```
Note the double slashes.  The first slash acts as an escape for the second, so the second is interpreted as an intentional backslash character instead of the desired `\n`, which indicates a carriage return.  So, either the translator messed this up or rosetta is automatically inserting extra slashes when it shouldn't.

**Comment by jbphet** [comment]
Here is what the string looks like in the translation utility at the moment.  From the translators point of view, this looks correct:
![image](https://user-images.githubusercontent.com/3082831/57108175-342f2800-6cef-11e9-839c-1d5237289198.png)

**Comment by jbphet** [comment]
A search of the `isotopes-and-atomic-mass` directory in babel shows a lot of double slashes followed by an 'n', see below.

![image](https://user-images.githubusercontent.com/3082831/57108288-75bfd300-6cef-11e9-9f53-22999f148f04.png)

**Comment by jbphet** [comment]
I just looked through the entire project, and only this sim (Isotopes and Atomic Mass) and Reactants, Products, and Leftovers are using the `\n` character in multi-line strings.  All other sims are using `<br>`.  It looks like the translation utility is messing up the '\n' characters.  I could correct the problem by replacing all usages of `\n` with `<br>`, or I could figure out why the translation utility is doing this and fix it.  I should probably do both, but I'm not sure of the state of rosetta at the moment - I think it might not be in a place where I can pull fixes in from master.  So, fixing it in the sims would be easier.

In either case, I will probably need to hand-edit existing translation files to fix this problem.

**Comment by jbphet** [comment]
I just looked through RPAL's translated string files, and I'm not seeing any occurrences of `\\n`.  This might mean that the problem where rosetta mangles the string was introduced after these translations were submitted.  I tested the Polish translation in rosetta using the 'Test' button, and saw this for the multi-line string (which translations to "No Reaction" with a line break):

![image](https://user-images.githubusercontent.com/3082831/57110708-b2db9380-6cf6-11e9-8a45-f2582d42a3ed.png)

The current live version looks like this:

![image](https://user-images.githubusercontent.com/3082831/57110840-2ed5db80-6cf7-11e9-8da4-8888dc3963ec.png)

So the problem has not always been present.  The Polish translation was submitted on Saturday, February 13, 2016, so the issue was introduced after that time.  I looked through the other non-mangled translations, and the _ga version was submitted on Monday, November 27, 2017, so the problem came in after that.

**Comment by jbphet** [comment]
@oliver-phet - I was finally able to find time to work on this while tackling some other translation issues. It is fixed in the live version, and should no longer be a problem for future translators.  For the record, this problem also afflicted the translations of this sim for the cs, pt_BR, uk, and fa locales.

Please let the translator who requested the fix know that the problem is, we believe, addressed.

**Comment by oliver-phet** [comment]
Translator notified, closing for now.
